# Generated by Django 4.2.6 on 2023-10-31 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=10)),
                ('report_type', models.CharField(choices=[('мідь', 'Мідь'), ('pon', 'Pon')], default='мідь', max_length=10)),
                ('cable_fo', models.IntegerField(blank=True, max_length=10, null=True)),
                ('cable_utp', models.IntegerField(blank=True, max_length=10, null=True)),
                ('router', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.locality')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriber.subscriber')),
            ],
        ),
    ]
