# Generated by Django 4.2.6 on 2023-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_connection_date_alter_report_cable_fo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='connection_date',
            field=models.DateField(blank=True),
        ),
    ]
