version: '3'
services:
  web:
    build: .
    restart: always
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: os.gotenv("POSTGRES_PASSWORD")
      POSTGRES_USER: os.gotenv("POSTGRES_USER")
      POSTGRES_DB: os.gotenv("POSTGRES_DB")
    ports:
      - 5433:5432
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

